/data/fass1/kirsten/result/classificationBenchmark/scripts/getting.py:12: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  parsed_yaml = yaml.load(c)
[33mProvided cores: 8[0m
[33mRules claiming more threads will be scaled down.[0m
[33mJob counts:
	count	jobs
	1	all
	2	areport
	2	clark
	2	clark_abundance
	7[0m
[32m[0m
[32mrule clark:
    input: /mnt/fass1/database/clark_database/targets.txt, /mnt/fass1/kirsten/data/promethion367.fastq
    output: /mnt/fass1/kirsten/result/classification/clark/default/promethion367_default.clark.classification.csv, /mnt/fass1/kirsten/result/classification/clark/default/promethion367_default.clark.classification_stats.csv
    jobid: 10
    benchmark: /mnt/fass1/kirsten/result/classification/benchmarks/default/promethion367_default.clark.benchmark.txt
    wildcards: PATH=/mnt/fass1/kirsten, sample=promethion367, run=default
    threads: 8[0m
[32m[0m
/data/fass1/kirsten/result/classificationBenchmark/scripts/getting.py:12: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  parsed_yaml = yaml.load(c)
CLARK version 1.2.5 (UCR CS&E. Copyright 2013-2018 Rachid Ounit, rouni001@cs.ucr.edu) 
Loading database [/mnt/fass1/kirsten/databases/clark/db_central_k31_t15625_s1610612741_m0.tsk.*] ...
Loading done (database size: 131353 MB read, with sampling factor 2)
Mode: Default,	Processing file: /mnt/fass1/kirsten/data/promethion367.fastq,	 using 8 CPU.

 - Assignment time: 17744.9 s. Speed: 116900 objects/min. (34573282 objects).
 - Results stored in /mnt/fass1/kirsten/result/classification/clark/default/promethion367_default.clark.classification.csv
[31mError in job clark while creating output files /mnt/fass1/kirsten/result/classification/clark/default/promethion367_default.clark.classification_stats.csv, /mnt/fass1/kirsten/result/classification/clark/default/promethion367_default.clark.classification.csv.[0m
[31mMissingOutputException in line 163 of /data/fass1/kirsten/result/classificationBenchmark/Snakefile:
Missing files after 5 seconds:
/mnt/fass1/kirsten/result/classification/clark/default/promethion367_default.clark.classification_stats.csv
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.[0m
[31mExiting because a job execution failed. Look above for error message[0m
[33mJob failed, going on with independent jobs.[0m
[32m[0m
[32mrule clark:
    input: /mnt/fass1/database/clark_database/targets.txt, /mnt/fass1/kirsten/data/promethion365.fastq
    output: /mnt/fass1/kirsten/result/classification/clark/default/promethion365_default.clark.classification.csv, /mnt/fass1/kirsten/result/classification/clark/default/promethion365_default.clark.classification_stats.csv
    jobid: 12
    benchmark: /mnt/fass1/kirsten/result/classification/benchmarks/default/promethion365_default.clark.benchmark.txt
    wildcards: PATH=/mnt/fass1/kirsten, sample=promethion365, run=default
    threads: 8[0m
[32m[0m
/data/fass1/kirsten/result/classificationBenchmark/scripts/getting.py:12: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  parsed_yaml = yaml.load(c)
CLARK version 1.2.5 (UCR CS&E. Copyright 2013-2018 Rachid Ounit, rouni001@cs.ucr.edu) 
Loading database [/mnt/fass1/kirsten/databases/clark/db_central_k31_t15625_s1610612741_m0.tsk.*] ...
Loading done (database size: 131353 MB read, with sampling factor 2)
Mode: Default,	Processing file: /mnt/fass1/kirsten/data/promethion365.fastq,	 using 8 CPU.
^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B^[[B                                                                                                ^C[33mTerminating processes on user request.[0m
[31mError in job clark while creating output files /mnt/fass1/kirsten/result/classification/clark/default/promethion365_default.clark.classification.csv, /mnt/fass1/kirsten/result/classification/clark/default/promethion365_default.clark.classification_stats.csv.[0m
[31mRuleException:
CalledProcessError in line 185 of /data/fass1/kirsten/result/classificationBenchmark/Snakefile:
Command 'CLARK --long -O /mnt/fass1/kirsten/data/promethion365.fastq -R /mnt/fass1/kirsten/result/classification/clark/default/promethion365_default.clark.classification -D /mnt/fass1/kirsten/databases/clark -n 8 -T /mnt/fass1/database/clark_database/targets.txt' returned non-zero exit status -2
  File "/data/fass1/kirsten/result/classificationBenchmark/Snakefile", line 185, in __rule_clark
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run[0m
[33mJob failed, going on with independent jobs.[0m
